### PR TITLE
Add Serilog and Seq and configure both

### PR DESCRIPTION
**Pull request by OlegXXL**

### CODE REVIEW

**Review by BorysKopytko — CHANGES_REQUESTED** [review]
Change pull request title to normal, mentioning Serilog and Seq starting from capital letter because it is its own name.

**Review by BorysKopytko — CHANGES_REQUESTED** [review]
"Add Logger Serilog and Seq is not fully good title", it'll sound better if it is "Add Serilog and Seq and configure both".

**Review by OlegXXL — COMMENTED** [review]
all okey

**Review by OlegXXL — COMMENTED** [review]
OK!

**Review by BorysKopytko — APPROVED** [review]

**Pull request merged**
